// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSMbOSOKltNFaTu-p54axFIZhRIphIjA',
    appId: '1:636292268320:web:02eb28d84aba4db42fd745',
    messagingSenderId: '636292268320',
    projectId: 'suyana-cdef0',
    authDomain: 'suyana-cdef0.firebaseapp.com',
    storageBucket: 'suyana-cdef0.firebasestorage.app',
    measurementId: 'G-S41Y48B2RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSPdRxRGDA33uQGl8XvkxzhllKKWEZdzA',
    appId: '1:636292268320:android:0715b8d756ef8dcf2fd745',
    messagingSenderId: '636292268320',
    projectId: 'suyana-cdef0',
    storageBucket: 'suyana-cdef0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxinXzBPsC7qTBarcWLIyyuPB5E1d3iH8',
    appId: '1:636292268320:ios:88ae5aaed5197e652fd745',
    messagingSenderId: '636292268320',
    projectId: 'suyana-cdef0',
    storageBucket: 'suyana-cdef0.firebasestorage.app',
    iosBundleId: 'com.example.suyana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxinXzBPsC7qTBarcWLIyyuPB5E1d3iH8',
    appId: '1:636292268320:ios:88ae5aaed5197e652fd745',
    messagingSenderId: '636292268320',
    projectId: 'suyana-cdef0',
    storageBucket: 'suyana-cdef0.firebasestorage.app',
    iosBundleId: 'com.example.suyana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaSMbOSOKltNFaTu-p54axFIZhRIphIjA',
    appId: '1:636292268320:web:1202fa6e72ba47042fd745',
    messagingSenderId: '636292268320',
    projectId: 'suyana-cdef0',
    authDomain: 'suyana-cdef0.firebaseapp.com',
    storageBucket: 'suyana-cdef0.firebasestorage.app',
    measurementId: 'G-HH5Z4P7L2D',
  );
}
